name: pyflowline_tutorial
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - cmake
  - make
  - numpy
  - gdal
  - netCDF4
  - mscorefonts 
  - matplotlib
  - cartopy
  - geopandas
  - libgdal-arrow-parquet
  - pyearth=0.1.26
  - pyflowline=0.3.10
